### ISSUE TITLE
[feature request] Put each VM for a deployment in to a sub directory

### ISSUE THREAD

**Issue by nehagjain15** [cloudfoundry/bosh-vsphere-cpi-release#133]
The request is to put each VM for a deployment in to a sub directory for easier mgmt inside vSphere.
So instead of having:
```
pcf_vms/
    vm-111
    vm-222
    vm-333
```
There would be something like:
```
pcf_vms/
    cf-123/
        vm-111
        vm-222
    mysql-456/
        vm-333
```
That way you can easily see which VMs correspond to a deployment.

**Comment by nehagjain15** [comment]
@yeshwantbabar

**Comment by EleanorRigby** [comment]
CPI's limitation is that there are no pre and post-deployment RPC calls. Since each CPI call is a separate process, CPI has no way to know when a deployment is getting created and when it is getting deleted.
As a consequence, CPI can create folders but will not be able to delete them. Several of such folder may pile up during several different deployments for PAS or PKS.

One way is to create and delete folders as VMs are created or deleted. To implement that, a mutex is needed to synchronize create and delete calls for a folder/vm. This is possible through a DRS lock but might severely slow down creation/deletion times for VMs.

The clearest solution is to have create deployment and delete deployment rpc calls where CPI can do some cloud prep stuff like creating folders, resource pools and vsphere verifiers etc..

Feel free to open if a solution is in sight.
