### ISSUE TITLE
Disabling vCenter Extension requirement

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry/bosh-vsphere-cpi-release#204]
**Describe the bug**
recent CPI versions require installation of a vCenter extension.   This is cosmetic only and some environments (VMC, VCF/SDDC) can't add that permission causing BOSH failures

**To Reproduce**
Remove BOSH user permission to add vcenter extensions
At BOSH create_stemcell time, when the extension is attempted to be added, see error "Permission to perform this operation was denied"

**CPI Error Log**
![image](https://user-images.githubusercontent.com/10640559/56170886-7131b580-5fa0-11e9-88ed-194b5cf1df7f.png)

**Expected behavior**
Users should not be required to have the extension, it adds limited value

**Comment by ktchen14** [comment]
I'm not sure that the problem here is the extension. Here's the code that ends up getting called in `create_stemcell`:

```ruby
    def create_cpi_extension(client)
      @vc_client = client

      return if extension_is_registered?

      logger.debug("Creating the vSphere CPI extension ...")
      cpi_extension = build_extension
      register_extension(cpi_extension)
    rescue => e
      logger.error("Failed to add extension with message #{e.inspect}")
    end
```

The error message that we'd expect to see isn't what's showing up in the Ops Manager logs here. And also note that the extension is totally optional (we fail with an error but proceed without the extension if it can't be added).

Can we see the CPI logs for this task?

If it is the extension then we should definitely fix this as the extension is a purely optional component. We totally understand that some users won't have the permissions (or desire) to use it.

**Comment by nehagjain15** [comment]
@svrc-pivotal As Kaiting pointed out that this feature was built to be optional. Can you share detailed cpi logs. Also, how do you know that 'Permission to perform this operation was denied' error was raised when extension was being registered?

**Comment by svrc-pivotal** [comment]
I'll dig further and get back to you.

**Comment by svrc-pivotal** [comment]
Apologies for the false alarm!   This was VMC folder permission related.
