### ISSUE TITLE
Cluster placement not working correctly for local storage persistent disks

### ISSUE THREAD

**Issue by cloud-dude** [cloudfoundry/bosh-vsphere-cpi-release#76]
Currently we seem to be running into a bug where if you specify local storage it does not validate if there is enough persistent disk space available on the host it is placing the VM on. Ephemeral disks are running on shared storage and persistent disks are running on local storage. We attached our bosh log for further clarification.
[bosh_deployment_log.txt](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/files/1830946/bosh_deployment_log.txt)

Based on the documentation this should be a supported configuration:
```When placing a VM, a cluster is chosen (along with a datastore) based on the VM's memory, ephemeral disk, and persistent disk requirements.
VMs are placed on clusters and datastores based on a weighted random algorithm. The weights are calculated by how many times the requested memory, ephemeral and persistent disk could fit on the cluster.
```
Source: https://bosh.io/docs/vsphere-cpi.html#vm-placement

```
bosh: 264.5.0
bosh-vsphere-cpi: 45
```

**Comment by yeshwantbabar** [comment]
Are you saying that there are multiple local datastores and CPI isn't choosing the one with more free space?

**Comment by ktchen14** [comment]
I think what's happening here is that typically we expect the ephemeral disks to be placed on local storage and the persistent disks to be placed on shared storage. However in this case the inverse has been configured.

When we choose a cluster for the VM we base the decision (partially) on whether or not a cluster has enough storage available to it to house the ephemeral disk.

Then later when BOSH asks us to attach the persistent disk we fail because the persistent storage pattern is configured to match only the local storage available to the VM and the local storage on the chosen host does not have enough free space for the persistent disk.

The problem here is that the vSphere CPI doesn't select a host for the VM; it selects a cluster and lets vSphere DRS choose the host. At this point vSphere DRS has no idea that we're about to attempt to create a large persistent disk on the host's local datastore.

**Comment by cppforlife** [comment]
@cloud-dude @ktchen14 did we regress on this functionality?

**Comment by ktchen14** [comment]
@cppforlife I don't think this ever worked reliably. We'll need to investigate if we can alert DRS to the fact that we're about to put a large disk onto the local datastore before it makes its decision.
